name: deploy

on:
  # push:
  #   branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: zip file
        run: zip -r pda_mini_back.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

      - name: upload to ec2 instance
        run:
